name: zenml_ci

on:
  push:
    branches: ["main"]

jobs:
  run-staging-workflow:
    runs-on: ubuntu-latest
    env:
      ZENML_HOST: ${{ secrets.ZENML_HOST }}
      ZENML_API_KEY: ${{ secrets.ZENML_API_KEY }}

    steps:
      - name: check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install requirements
        run: |
          pip3 install -r requirements.txt
          
      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: connect to Zenml server
        run: |
          cat <<'EOF' > zenml_login.exp
          #!/usr/bin/expect -f
          set timeout 10
          set host $env(ZENML_HOST)
          set api_key $env(ZENML_API_KEY)
          spawn zenml login $host --api-key
          expect "API key:"
          send "$api_key\r"
          expect eof
          EOF
          chmod +x zenml_login.exp
          ./zenml_login.exp

      - name: confirm zenml client is connected to zenml server
        run: |
          zenml status

      - name: run pipeline
        run: |
          python first.py
        
